version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production