version: "3.9"
services:
  web:
    image: node:18-alpine
    container_name: web-app
    working_dir: /app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production